#Available languages
#en_US
#es_ES
locale: en_US

# This is the en_US.yml version for reference.
# ONLY EDIT ONCE ALL LANGUAGE FILES HAVE BEEN UPDATED.
languageFile: 1

# Blocks that you can convert into a game table
gameTables:
  - EMERALD_BLOCK
  - CHISELED_STONE_BRICKS